### PR TITLE
Consider local keybindings when moving commands for the Motion state.

### PR DESCRIPTION
**Pull request by okamsn**
- Add the library Compat (https://elpa.gnu.org/packages/compat.html), which makes available the function `keymap-local-lookup` to Emacs older than 29.1. The new `keymap-` functions are recommended over older functions like `lookup-key`.

- Instead of directly binding `H-j` to what was bound to `j`, for example, bind `H-j` to an interactive lambda which first checks whether there is a local binding for `j`.  If there is, use that.  If there is not, then call the orignal command bound to `j`.

This seems to fix using the overrides in Magit buffers (see #493), where the command bound to `H-k` seems to be based on where point is located when `meow--save-origin-commands` is run.

### CODE REVIEW

**Comment by DogLooksGood** [comment]
Hey, thanks for the contribution.  

We want to keep meow free of dependencies, so we don't want to introduce `compact` library. I guess we can port it if we really need it.

**Comment by okamsn** [comment]
OK, I've removed the use of Compat and copied the relevant portion of the definition.

This change works for me on Emacs 29.1. What else would you like changed?

**Comment by DogLooksGood** [comment]
I'm quite busy these days.  Later I'll check the updates and merge.

**Comment by norris-young** [comment]
This works for me. Will you merge it?

**Comment by DogLooksGood** [comment]
I'll do some test and merge it.

**Pull request merged**
