### PR TITLE
Update meow--current-state to nil, when disabled

### PR DESCRIPTION
**Pull request by Inc0n**
This is to address issue: https://github.com/meow-edit/meow/issues/258.
Note: my tab width is set to 8.

### CODE REVIEW

**Comment by DogLooksGood** [comment]
I'm a bit busy for these days, I'll back to this once I have time.

**Comment by eshrh** [comment]
I'd prefer you used `meow--disable-state` like you suggested in the issue. It just seems better...

**Comment by Inc0n** [comment]
I have just updated the patch correspondingly

**Comment by eshrh** [comment]
oh oops, that's totally my bad, disable-current-state also calls the same mode function, which calls disable-current-state, and so on leading to a lisp nesting stack error. Setq-local commit doesn't have this issue. Could you revert back to your earlier commit or rebase/remove it?

**Comment by Inc0n** [comment]
Fair enough, done.

**Pull request merged**
