### PR TITLE
Add cheatsheet layout for Colemak-DH

### PR DESCRIPTION
**Pull request by plattfot**
It is a slight modification to the Colemak layout, where `d`, `g` and `b` on the "right hand" and `h` and `m` on the "left hand" has been moved. See [link](https://colemakmods.github.io/mod-dh/) for more info.

The colemak cheatsheet layout kind of works but it was enough confusing for me when I first started using meow that I ended up writing a specific cheatsheet for the Mod DH. And I thought it might be good to share.

### CODE REVIEW

**Comment by eshrh** [comment]
Nice! Could you add a quick note to the KEYBINDING_COLEMAK.org just saying that this variable exists, at the top or bottom? Otherwise i'm not sure how anyone who uses colemak dh would discover it.

**Comment by plattfot** [comment]
Yeah, would be hard to discover otherwise. Do you want me to squash the commits or are two commits fine?

**Comment by eshrh** [comment]
squash please!

**Comment by eshrh** [comment]
nvm, it's just one button to squash them on my end.

**Pull request merged**
