### PR TITLE
Improve wording and punctuation in meow-tutor

### PR DESCRIPTION
**Pull request by yusi1**
I noticed some more errors in meow-tutor...

### CODE REVIEW

**Comment by DogLooksGood** [comment]
Let me resolve the conflicts?

**Comment by yusi1** [comment]
> Let me resolve the conflicts?

Yes, this would be great

**Comment by DogLooksGood** [comment]
Let's merge this?

**Comment by yusi1** [comment]
Sure!

**Comment by yusi1** [comment]
sry for the trouble, I am a beginner at Git

**Comment by DogLooksGood** [comment]
Don't mind, thanks for your contribution!

**Pull request merged**
